spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
  datasource:
    url: jdbc:mysql://localhost:3306/devita?serverTimezone=Asia/Seoul
    username: milo
    password: 5188
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: "608bb071909d67d6bf0cb0f3b3645ece"
            client-secret: "RqHfTj8Y2f81YVeggsm50vqzPHTUlPQ8"
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

jwt:
  secret:
    access: "5/QWm//BsCVJ41ORLonFufODCm9NWn0zsGK8/Wff+Lo="
    refresh: "0ZFrg+SUY41noBVrteelT1EuHJChth7S0dbykMWSYFM="
  expiration:
    access: 3600000  # 1??
    refresh: 604800000  # 7?

server:
  error:
    whitelabel:
      enabled: false

logging:
  level:
    root: INFO
    com.example.shoppingmallproject: DEBUG
    org.springframework.security: DEBUG
